[project]
name = "sql-srs"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Slayn", email = "neoslayn@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "duckdb>=1.5.5",
    "pandas>=3.0.5",
    "streamlit>=1.63.0",
]

[project.scripts]
sql-srs = "sql_srs:main"

[build-system]
requires = ["uv_build>=0.12.9,<0.13.0"]
build-backend = "uv_build"
